server:
  port: 8011

# ant样式匹配，适配路由请求
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-5yd3gvqp50014o.rwlb.rds.aliyuncs.com:3306/download_db?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&autoReconnect=true
    username: hc
    password: Shc@123



